services:
  db:
    image: postgres:16-alpine
    container_name: db
    env_file:
        - .env
    ports: [5432:5432]
    volumes:
        - postgres:/var/lib/postgresql/data
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 3s
        timeout: 3s
        retries: 5
  web:
    image: ruby:3.4.1
    container_name: web
    user: root
    # command: bash -c "rm -rf tmp/pids/server.pid && bin/setup && bundle exec rails s -b 0.0.0.0 -p 3000"
    command: bash
    working_dir: /app
    ports: [3000:3000]
    volumes:
        - .:/app
        - rubygems:/usr/local/bundle
    env_file:
        - .env
    tty: true
    stdin_open: true
    depends_on:
        - db
volumes:
  postgres:
  rubygems:

